---
title: "visualization"
author: "Shiyu KANG"
date: "2026-10-01"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```

Now we have everything we need!

```{r}
weather_df
```

Let's make a scatterplot!

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

I always like the dataframe first

```{r}
ggp_temp_scatterplot = 
  weather_df |>
  ggplot(aes(x = tmin,y = tmax)) +
  geom_point()

ggp_temp_scatterplot

```

##geom_point()是干什么的，alpha, aes, se

```{r}
weather_df |>
  ggplot(aes(x = tmin,y = tmax, color = name)) +
  geom_point(alpha = 0.5)+
  geom_smooth(se = FALSE)

```


##为什么没图片生成了
```{r}
weather_df |>
  ggplot(aes(x = tmin,y = tmax)) +
  geom_point(aes(color = name),alpha = 0.5)+
  geom_smooth(se = FALSE)
```

Show faceting

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) + 
  facet_grid(cols = vars(name))
```

Let's look at something else
##size = prcp是什么意思，把点变成小圈吗
```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)
```

make a plot of central park tmax v tmin only, and convert temperatures to fahrenheit
```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax = tmax*(9 / 5) + 32,
    tmin = tmin*(9 / 5) + 32
  ) |>
  ggplot(aes(x = tmin,y = tmax)) +
  geom_point()
```

##hex plot
```{r}

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()

```


```{r}
weather_df |>
  ggplot(aes(x = tmax)) +
  geom_histogram()
```

```{r}
weather_df |>
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(. ~name)
```

Density plots are great!

```{r}
weather_df |>
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.5)
```

Box plots 
```{r}
weather_df |>
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

Violin 

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```

Ridge plots
```{r}
weather_df |>
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```

## Save some of my plots

```{r}
ggp_weather =
  weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  facet_grid(. ~name)

ggp_weather

ggsave("ggp_weather.pdf", ggp_weather)
```

```{r fig.width = 12, fig.height = 12}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```



