---
title: "02_viz"
author: "Shiyu KANG"
date: "2026-10-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)

library(p8105.datasets)
data("weather_df")
```

```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  labs(
    title = "Temperature",
    x = "Max Temperature (C)",
    y = "Min Temperature (C)",
    color = "Location",
    caption = "Data from NOAA"
  ) +
  scale_x_continuous(
    breaks = c(-10, 0, 15),
    labels = c("- 10 C","0","Fifteen")
  ) +
  scale_y_continuous(
    trans = "sqrt",
    position = "right"
  )

```


Let's look at the color

```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  scale_color_hue(h = c(100,300))
```


```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE
  )
```


##Themes 
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax,color = name)) +
  geom_point() +
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE
  ) +
  theme_classic() +
  theme(legend.position = "bottom")
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax,color = name)) +
  geom_point() +
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE
  ) +
  theme_classic() +
  theme(legend.position = "bottom") +
  theme_minimal()
```


Update the tmax vs date plot
```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  labs(
    title = "Seasonal Trend in Max Temp",
    x = "Date",
    y = "Max Temp"
  ) +
  viridis::scale_color_viridis(
    name = "location",
    discrete = TRUE
  ) +
  theme_classic() +
  theme_minimal() +
  theme(legend.position = "bottom")
```


##Two more plot things
```{r}
central_park_df = 
  weather_df |>
  filter(name == "CentralPark_NY")

molokai_df = 
  weather_df |>
  filter(name == "Molokai_HI")

ggplot(molokai_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park_df)
```


multiple panels with different plot types
```{r}
ggp_tmax_tmin = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() +
  theme(legend.position = "none")

ggp_prcp_density = 
  weather_df |>
  filter(prcp > 0) |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.5) +
  theme(legend.position = "none")

ggp_seasonal = 
  weather_df |>
  ggplot(aes(x = date,y = tmax, color = name)) +
  geom_point() +
  theme(legend.position = "bottom")

(ggp_tmax_tmin + ggp_prcp_density) / ggp_seasonal

```


## Data Manipulation

Start with factors

boxplots

```{r}
weather_df |>
  mutate(name = fct_relevel(name, c("Molakai_HI","CentralPark_NY","Waterhole_WA"))) |>
  ggplot(aes(x = name ,y = tmax)) +
  geom_boxplot() 
```


```{r}
weather_df |>
  mutate(name = fct_reorder(name, tmax)) |>
  ggplot(aes(x = name ,y = tmax)) +
  geom_boxplot() 
```


Make that distribution plot

```{r}
weather_df |>
  select(name, tmax, tmin) |>
  pivot_longer(
    tmax:tmin,
    names_to =  "observation",
    values_to = "temp"
  ) |>
  ggplot(aes(x = temp, fill = observation)) +
  geom_density(alpha = .5) +
  facet_grid(. ~name) 
```

Make an FAS plot

```{r}
pups_df = 
  read_csv("~/Desktop/Biostats/Data Science/data_wrangling_1/data/FAS_pups.csv",
           skip = 3,
           na = c("",".","NA")) |>
  janitor::clean_names()

litters_df = 
  read_csv(
    "~/Desktop/Biostats/Data Science/data_wrangling_1/data/FAS_litters.csv",
    na = c("",".","NA")) |>
  janitor::clean_names() |>
  separate(group, into = c("dose","day_of_tx"), 3)

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")

fas_df |>
  select(dose, day_of_tx, starts_with("pd")) |>
  pivot_longer(
    starts_with("pd"),
    names_to = "outcome",
    values_to = "pn_day"
  ) |>
  drop_na() |>
  mutate(outcome = forcats::fct_reorder(outcome, pn_day, median)) |> 
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_violin() + 
  facet_grid(day_of_tx ~ outcome)
```

